services:
  db:
    build: ./postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres/db_seed_data:/data
  ui:
    build: ./web-ui
    container_name: ui
    restart: always
    ports: 
      - "80:80"
    environment:
      - NODE_ENV=production
  api:
    build: ./openai-api
    container_name: api
    restart: always
    ports: 
      - "5000:5000"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=db
      - OPENAI_API_KEY=xxx